### ISSUE TITLE
Key consul version 1.6.9 missing please could you added it.

### ISSUE THREAD

**Issue by alexis-spx** [calvn/chocolatey-consul#63]
We are currently running different versions of consul 1.4.x -1.6.x and want to upgrade to the latest.

Consul recommends us upgrading everything to 1.6.9 then to 1.8.4.  However you do not seem to have 1.6.9, please could you add this key package.

https://www.consul.io/docs/upgrading/instructions/upgrade-to-1-6-x
https://www.consul.io/docs/upgrading/instructions/upgrade-to-1-8-x

Cheers.

**Comment by calvn** [comment]
Hi there! Apologies for the delay on this one. I'm working on getting the 1.6.x series release up-to-date so 1.6.9 should be available shortly.

**Comment by calvn** [comment]
1.6.9 is available now, thanks for bringing this up!
