### ISSUE TITLE
Bundled UI package now deprecated

### ISSUE THREAD

**Issue by kitforbes** [calvn/chocolatey-consul#8]
The bundled UI package is no longer required, as it is included within the Consul binary.

> ==> If using Consul version 0.7.0 or later, the web UI is included in the binary so use ui to enable it

You can enable the UI with a command line flag (`-ui`) or by adding a boolean to your config file for `"ui": true`. It would be good if you could remove the bundled UI from this package.

**Comment by calvn** [comment]
Fixed in #9
